// you need to change globals.js as well
exports.SOCKET_TYPE = {
  INIT_CONNECTION: "INIT_CONNECTION",
  PLAYERS_CHANGED: "PLAYERS_CHANGED",
  RECONNECT: "RECONNECT",
  CHANGE_STATE: "CHANGE_STATE",
  GET_THEME: "GET_THEME",
  CHANGE_THEME_VOTE: "CHANGE_THEME_VOTE",
  SEND_MESSAGE: "SEND_MESSAGE",
  SEND_ANSWER: "SEND_ANSWER",
  SHOW_ANSWER: "SHOW_ANSWER",
  VOTE: "VOTE",
  VOTE_DONE: "VOTE_DONE",
  CALC_POINTS: "CALC_POINTS",
};
exports.STATE = {
  BEFORE_GAME: "BEFORE_GAME",
  ANSWER: "ANSWER",
  SHOW_ANSWER: "SHOW_ANSWER",
  VOTE: "VOTE",
  SHOW_POINTS: "SHOW_POINTS",
};
