export const STATE = {
  BEFORE_GAME: "BEFORE_GAME",
  ANSWER: "ANSWER",
  VOTE: "VOTE",
};
export const SOCKET_TYPE = {
  CHANGE_STATE: "CHANGE_STATE",
  PLAYERS_CHANGED: "PLAYERS_CHANGED",
  SEND_MESSAGE: "SEND_MESSAGE",
};
