export const STATE = {
  BEFORE_GAME: "BEFORE_GAME",
  ANSWER: "ANSWER",
  SHOW_ANSWER: "SHOW_ANSWER",
  VOTE: "VOTE",
};

// you need to change server.js as well
export const SOCKET_TYPE = {
  PLAYERS_CHANGED: "PLAYERS_CHANGED",
  CHANGE_STATE: "CHANGE_STATE",
  GET_THEME: "GET_THEME",
  SEND_MESSAGE: "SEND_MESSAGE",
  SEND_ANSWER: "SEND_ANSWER",
};
